/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as BookingShowIdRouteImport } from './routes/booking.$showId'
import { Route as SeatsShowIdRouteImport } from './routes/seats.$showId'
import { Route as ShowsIdRouteImport } from './routes/shows.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingShowIdRoute = BookingShowIdRouteImport.update({
  id: '/booking/$showId',
  path: '/booking/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsShowIdRoute = SeatsShowIdRouteImport.update({
  id: '/seats/$showId',
  path: '/seats/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIdRoute = ShowsIdRouteImport.update({
  id: '/shows/$id',
  path: '/shows/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/tickets': typeof TicketsRoute
  '/booking/$showId': typeof BookingShowIdRoute
  '/seats/$showId': typeof SeatsShowIdRoute
  '/shows/$id': typeof ShowsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/tickets': typeof TicketsRoute
  '/booking/$showId': typeof BookingShowIdRoute
  '/seats/$showId': typeof SeatsShowIdRoute
  '/shows/$id': typeof ShowsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/tickets': typeof TicketsRoute
  '/booking/$showId': typeof BookingShowIdRoute
  '/seats/$showId': typeof SeatsShowIdRoute
  '/shows/$id': typeof ShowsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/tickets'
    | '/booking/$showId'
    | '/seats/$showId'
    | '/shows/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/tickets'
    | '/booking/$showId'
    | '/seats/$showId'
    | '/shows/$id'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/tickets'
    | '/booking/$showId'
    | '/seats/$showId'
    | '/shows/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  TicketsRoute: typeof TicketsRoute
  BookingShowIdRoute: typeof BookingShowIdRoute
  SeatsShowIdRoute: typeof SeatsShowIdRoute
  ShowsIdRoute: typeof ShowsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$showId': {
      id: '/booking/$showId'
      path: '/booking/$showId'
      fullPath: '/booking/$showId'
      preLoaderRoute: typeof BookingShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats/$showId': {
      id: '/seats/$showId'
      path: '/seats/$showId'
      fullPath: '/seats/$showId'
      preLoaderRoute: typeof SeatsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$id': {
      id: '/shows/$id'
      path: '/shows/$id'
      fullPath: '/shows/$id'
      preLoaderRoute: typeof ShowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  TicketsRoute: TicketsRoute,
  BookingShowIdRoute: BookingShowIdRoute,
  SeatsShowIdRoute: SeatsShowIdRoute,
  ShowsIdRoute: ShowsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
