/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as BookingShowIdRouteImport } from './routes/booking.$showId'
import { Route as SeatsShowIdRouteImport } from './routes/seats.$showId'
import { Route as ShowsIdRouteImport } from './routes/shows.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminHallsRouteImport } from './routes/_authenticated/admin.halls'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminSessionsRouteImport } from './routes/_authenticated/admin.sessions'
import { Route as AuthenticatedAdminShowsRouteImport } from './routes/_authenticated/admin.shows'
import { Route as AuthenticatedAdminTheatersRouteImport } from './routes/_authenticated/admin.theaters'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedConfirmationBookingIdRouteImport } from './routes/_authenticated/confirmation.$bookingId'
import { Route as AuthenticatedPaymentBookingIdRouteImport } from './routes/_authenticated/payment.$bookingId'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedStaffCheckinRouteImport } from './routes/_authenticated/staff.checkin'
import { Route as AuthenticatedTicketTicketIdRouteImport } from './routes/_authenticated/ticket.$ticketId'
import { Route as ApiPublicPosterSplatRouteImport } from './routes/api/public/poster.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BookingShowIdRoute = BookingShowIdRouteImport.update({
  id: '/booking/$showId',
  path: '/booking/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsShowIdRoute = SeatsShowIdRouteImport.update({
  id: '/seats/$showId',
  path: '/seats/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIdRoute = ShowsIdRouteImport.update({
  id: '/shows/$id',
  path: '/shows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHallsRoute = AuthenticatedAdminHallsRouteImport.update({
  id: '/halls',
  path: '/halls',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShowsRoute = AuthenticatedAdminShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTheatersRoute =
  AuthenticatedAdminTheatersRouteImport.update({
    id: '/theaters',
    path: '/theaters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedConfirmationBookingIdRoute =
  AuthenticatedConfirmationBookingIdRouteImport.update({
    id: '/confirmation/$bookingId',
    path: '/confirmation/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentBookingIdRoute =
  AuthenticatedPaymentBookingIdRouteImport.update({
    id: '/payment/$bookingId',
    path: '/payment/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffCheckinRoute =
  AuthenticatedStaffCheckinRouteImport.update({
    id: '/checkin',
    path: '/checkin',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedTicketTicketIdRoute =
  AuthenticatedTicketTicketIdRouteImport.update({
    id: '/ticket/$ticketId',
    path: '/ticket/$ticketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPosterSplatRoute = ApiPublicPosterSplatRouteImport.update({
  id: '/api/public/poster/$',
  path: '/api/public/poster/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRoute
  '/booking/$showId': typeof BookingShowIdRoute
  '/seats/$showId': typeof SeatsShowIdRoute
  '/shows/$id': typeof ShowsIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/halls': typeof AuthenticatedAdminHallsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/admin/theaters': typeof AuthenticatedAdminTheatersRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/confirmation/$bookingId': typeof AuthenticatedConfirmationBookingIdRoute
  '/payment/$bookingId': typeof AuthenticatedPaymentBookingIdRoute
  '/staff/checkin': typeof AuthenticatedStaffCheckinRoute
  '/ticket/$ticketId': typeof AuthenticatedTicketTicketIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/api/public/poster/$': typeof ApiPublicPosterSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/booking/$showId': typeof BookingShowIdRoute
  '/seats/$showId': typeof SeatsShowIdRoute
  '/shows/$id': typeof ShowsIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/halls': typeof AuthenticatedAdminHallsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/admin/theaters': typeof AuthenticatedAdminTheatersRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/confirmation/$bookingId': typeof AuthenticatedConfirmationBookingIdRoute
  '/payment/$bookingId': typeof AuthenticatedPaymentBookingIdRoute
  '/staff/checkin': typeof AuthenticatedStaffCheckinRoute
  '/ticket/$ticketId': typeof AuthenticatedTicketTicketIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/api/public/poster/$': typeof ApiPublicPosterSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/booking/$showId': typeof BookingShowIdRoute
  '/seats/$showId': typeof SeatsShowIdRoute
  '/shows/$id': typeof ShowsIdRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/halls': typeof AuthenticatedAdminHallsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/_authenticated/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/_authenticated/admin/theaters': typeof AuthenticatedAdminTheatersRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/confirmation/$bookingId': typeof AuthenticatedConfirmationBookingIdRoute
  '/_authenticated/payment/$bookingId': typeof AuthenticatedPaymentBookingIdRoute
  '/_authenticated/staff/checkin': typeof AuthenticatedStaffCheckinRoute
  '/_authenticated/ticket/$ticketId': typeof AuthenticatedTicketTicketIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/api/public/poster/$': typeof ApiPublicPosterSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/profile'
    | '/staff'
    | '/tickets'
    | '/booking/$showId'
    | '/seats/$showId'
    | '/shows/$id'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/halls'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/shows'
    | '/admin/theaters'
    | '/admin/tickets'
    | '/admin/users'
    | '/confirmation/$bookingId'
    | '/payment/$bookingId'
    | '/staff/checkin'
    | '/ticket/$ticketId'
    | '/admin/'
    | '/staff/'
    | '/api/public/poster/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/tickets'
    | '/booking/$showId'
    | '/seats/$showId'
    | '/shows/$id'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/halls'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/shows'
    | '/admin/theaters'
    | '/admin/tickets'
    | '/admin/users'
    | '/confirmation/$bookingId'
    | '/payment/$bookingId'
    | '/staff/checkin'
    | '/ticket/$ticketId'
    | '/admin'
    | '/staff'
    | '/api/public/poster/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/_authenticated/staff'
    | '/_authenticated/tickets'
    | '/booking/$showId'
    | '/seats/$showId'
    | '/shows/$id'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/halls'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/sessions'
    | '/_authenticated/admin/shows'
    | '/_authenticated/admin/theaters'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/confirmation/$bookingId'
    | '/_authenticated/payment/$bookingId'
    | '/_authenticated/staff/checkin'
    | '/_authenticated/ticket/$ticketId'
    | '/_authenticated/admin/'
    | '/_authenticated/staff/'
    | '/api/public/poster/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingShowIdRoute: typeof BookingShowIdRoute
  SeatsShowIdRoute: typeof SeatsShowIdRoute
  ShowsIdRoute: typeof ShowsIdRoute
  ApiPublicPosterSplatRoute: typeof ApiPublicPosterSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/booking/$showId': {
      id: '/booking/$showId'
      path: '/booking/$showId'
      fullPath: '/booking/$showId'
      preLoaderRoute: typeof BookingShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats/$showId': {
      id: '/seats/$showId'
      path: '/seats/$showId'
      fullPath: '/seats/$showId'
      preLoaderRoute: typeof SeatsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$id': {
      id: '/shows/$id'
      path: '/shows/$id'
      fullPath: '/shows/$id'
      preLoaderRoute: typeof ShowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/halls': {
      id: '/_authenticated/admin/halls'
      path: '/halls'
      fullPath: '/admin/halls'
      preLoaderRoute: typeof AuthenticatedAdminHallsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sessions': {
      id: '/_authenticated/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shows': {
      id: '/_authenticated/admin/shows'
      path: '/shows'
      fullPath: '/admin/shows'
      preLoaderRoute: typeof AuthenticatedAdminShowsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/theaters': {
      id: '/_authenticated/admin/theaters'
      path: '/theaters'
      fullPath: '/admin/theaters'
      preLoaderRoute: typeof AuthenticatedAdminTheatersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/confirmation/$bookingId': {
      id: '/_authenticated/confirmation/$bookingId'
      path: '/confirmation/$bookingId'
      fullPath: '/confirmation/$bookingId'
      preLoaderRoute: typeof AuthenticatedConfirmationBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/$bookingId': {
      id: '/_authenticated/payment/$bookingId'
      path: '/payment/$bookingId'
      fullPath: '/payment/$bookingId'
      preLoaderRoute: typeof AuthenticatedPaymentBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/checkin': {
      id: '/_authenticated/staff/checkin'
      path: '/checkin'
      fullPath: '/staff/checkin'
      preLoaderRoute: typeof AuthenticatedStaffCheckinRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/ticket/$ticketId': {
      id: '/_authenticated/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/poster/$': {
      id: '/api/public/poster/$'
      path: '/api/public/poster/$'
      fullPath: '/api/public/poster/$'
      preLoaderRoute: typeof ApiPublicPosterSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminHallsRoute: typeof AuthenticatedAdminHallsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminShowsRoute: typeof AuthenticatedAdminShowsRoute
  AuthenticatedAdminTheatersRoute: typeof AuthenticatedAdminTheatersRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminHallsRoute: AuthenticatedAdminHallsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
  AuthenticatedAdminShowsRoute: AuthenticatedAdminShowsRoute,
  AuthenticatedAdminTheatersRoute: AuthenticatedAdminTheatersRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffCheckinRoute: typeof AuthenticatedStaffCheckinRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffCheckinRoute: AuthenticatedStaffCheckinRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedConfirmationBookingIdRoute: typeof AuthenticatedConfirmationBookingIdRoute
  AuthenticatedPaymentBookingIdRoute: typeof AuthenticatedPaymentBookingIdRoute
  AuthenticatedTicketTicketIdRoute: typeof AuthenticatedTicketTicketIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedConfirmationBookingIdRoute:
    AuthenticatedConfirmationBookingIdRoute,
  AuthenticatedPaymentBookingIdRoute: AuthenticatedPaymentBookingIdRoute,
  AuthenticatedTicketTicketIdRoute: AuthenticatedTicketTicketIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingShowIdRoute: BookingShowIdRoute,
  SeatsShowIdRoute: SeatsShowIdRoute,
  ShowsIdRoute: ShowsIdRoute,
  ApiPublicPosterSplatRoute: ApiPublicPosterSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
